### ISSUE TITLE
Please add option to reinstall

### ISSUE THREAD

**Issue by gradinkov** [bviktor/kf2-centos#6]
Often needed due to space constraints.

**Comment by bviktor** [comment]
Agreed. Also necessary when lots of things change and it's easier to just reinstall, but not possible currently because various blockers:

- useradd
- path edit
- firewall new service & cp
- autokick curl installs

Check if these are already in place, force rewrites on other existing files, and add an option to nuke `/home/steam` and start fresh. Make sure to create a backup of `/home/steam/Config`.

**Comment by bviktor** [comment]
Done
